def eventListReader(fileLocation):
    '''Methode for reading the list of merger event id with their corespoinding
    detectors. The list should have been generated by the mergerEventGen script

    Events will be returned as a dict data type with the key being the event ID
    while the value is points too will be a list of the detectors that measured
    the event
    '''
    outputFormater = namedtuple('event',['event_id','detector_ids'])
    #return init
    events = []
    with open(fileLocation,'r') as doc:
        for line in doc:
            line = str(line)
            if not '#' in line:
                #converting string to a list
                line = [c[:-1] if '\n' in c else c for c in line.split(' ')]
                #isolating the event id and the detectors that measured it
                eventID = line[0]
                eventDetectors = line[1:]
                #appending the event to the dict
                events.append(outputFormater(eventID,eventDetectors))
    return(events)
